name: sideswap_logger
description: Sideswap custom logger
version: 0.0.9

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
