name: sideswap_logger
description: Sideswap custom logger
version: 0.0.7

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.5"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
